# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7d8252dbc4f84a0adaa1cec949efe47be5829e933edb685e122f2a24fa2d4cf2c4e0340665148f93ba72ca88a4812f8d8741cfb2c9c01ecac5775eaf3a84bc9

test:
  secret_key_base: e8d45ed06f6422f33bb9deb5ae94e32311e4696c2ef39449b0c2cea98d0d04369f1ed2169d1fc14fdf295413109be11bfcf7c0ef5ac90bd7c2d5300abc7b9cbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
